import type { ModuleDef } from "../types";

export const MATRIX: ModuleDef = {
  id: "matrix",
  title: "Hacking for Dummies",
  tagline: "Break into the Matrix without getting your brain fried.",
  intro:
    "Eleven short lessons that turn the Matrix chapter into plain language: what your numbers mean, why hackers get caught, and how to pick the right action. Finish with a live mission against a corporate host.",
  glossary: {
    Matrix: "The worldwide wireless network. Almost every device with a chip is on it.",
    Icon: "How the Matrix draws something: a person, a device, a file, a program, a whole building.",
    Persona: "Your icon in the Matrix. Technomancers, agents and IC have personas too.",
    Host: "A big Matrix place, like a corporate network or a club. It has its own rules, security and rating.",
    PAN: "Personal Area Network: your commlink or deck plus the devices linked to it. Hack the PAN and you reach everything in it.",
    Commlink: "The pocket computer everyone owns. Fine for calls and searches, but it has no hacking stats.",
    Cyberdeck: "A hacker's computer. It carries the Attack, Sleaze, Data Processing and Firewall ratings you need for hacking.",
    AR: "Augmented reality. You stay in your body and the Matrix is drawn over the real world.",
    VR: "Virtual reality. Your senses live inside the Matrix. Faster, but riskier.",
    "Cold-sim": "VR with a safety filter. A bit slower, much less dangerous.",
    "Hot-sim": "VR without the filter. Fastest and most dangerous. Illegal almost everywhere.",
    Dumpshock: "The damage from being thrown out of VR. 3 Stun in cold-sim, 3 Physical in hot-sim, resisted with Willpower. You also cannot use Edge for (10 minus Willpower) minutes.",
    Biofeedback: "Matrix damage that skips your device and hurts your body. Resisted with Willpower.",
    ASDF: "Attack, Sleaze, Data Processing, Firewall: the four Matrix stats that replace your physical attributes.",
    Attack: "Your offence. The crowbar. Drives Brute Force, Data Spike and Tarpit.",
    Sleaze: "Your stealth. The lockpick. Drives Probe and Backdoor Entry.",
    "Data Processing": "Raw computing power. How fast you are, how many programs you can run, and half of your defense.",
    Firewall: "Your armor. Half of your defense, and what you roll to resist Matrix damage.",
    "Attack Rating": "Attack plus Sleaze. Compared with the other side's Defense Rating to see who gains Edge.",
    "Defense Rating": "Data Processing plus Firewall.",
    Edge: "Your luck resource. Big gaps in Attack Rating versus Defense Rating give bonus Edge.",
    "Net hits": "Your hits minus the other side's hits. Often added to the effect of the action.",
    Cracking: "The skill for illegal Matrix actions.",
    Electronics: "The skill for legal Matrix actions.",
    Legal: "Allowed actions. They never raise your Overwatch Score by themselves.",
    Illegal: "Hacking-type actions. Every one of them risks raising your Overwatch Score.",
    GOD: "Grid Overwatch Division. The Matrix police. They keep your Overwatch Score.",
    "Overwatch Score": "A hidden counter GOD keeps on you. Illegal actions push it up. At 40 you get Convergence.",
    OS: "Overwatch Score.",
    Convergence: "What happens at OS 40: your last illegal device is bricked, you are dumped, and your location is reported.",
    Bricked: "A device whose Matrix condition monitor is full. It is dead until repaired.",
    Outsider: "The first level of access. You can look around and talk to others, nothing more.",
    User: "Second level of access. You can read things and use basic functions.",
    Admin: "Top level of access. You can change settings and switch devices on or off.",
    Backdoor: "A hidden way back in that you create with a successful Probe.",
    IC: "Intrusion Countermeasures, also called ice. Security programs that live in a host and attack intruders.",
    Spider: "A living security hacker who defends a host.",
    "Link-lock": "A signal that stops your device from leaving the Matrix. You must beat it with a Jack Out test.",
    "Matrix condition monitor": "The boxes of Matrix damage a device can take: device rating divided by 2 (round up) plus 8.",
    "Major action": "Your main action for the turn. Most hacking is a Major action.",
    "Minor action": "A quick extra action, like switching to AR or changing icon.",
    Technomancer: "A person who hacks the Matrix with their mind using Resonance instead of a deck.",
    Resonance: "The technomancer's version of Magic. It powers complex forms and sprites.",
    Noise: "Interference that makes Matrix tests harder. Signal Scrubber and Signal Scream push it back.",
    "Run silent": "Switching your device so it stops answering public queries. Hard to spot, but not invisible.",
  },
  lessons: [
    {
      id: "what-is-the-matrix",
      title: "What the Matrix actually is",
      blurb: "Icons, devices, and the two ways to plug in.",
      minutes: 5,
      blocks: [
        { t: "p", text: "The [[Matrix]] is the world's wireless network. Your commlink, the door lock, the traffic camera and the gun with a smartlink are all online, and each one shows up in the Matrix as an **icon**." },
        { t: "p", text: "People are drawn as [[Persona|personas]], and they can look like anything: a cat-headed person, a walking tree, a shapeshifting robot. Devices look like objects. Files look like paper or discs. A [[Host|host]] looks like a building, and the building tells you what the owner thinks of visitors." },
        { t: "callout", tone: "story", text: "A host that looks like a cozy mountain cabin wants you relaxed and spending money. One that looks like a castle with razor wire on the turrets and piranhas in the moat wants you gone." },
        { t: "p", text: "Hackers do not type endless code. They walk up to icons and do things to them. Every thing you can do has a name, like Probe or Data Spike, and those names are the verbs of this module." },
        { t: "h", text: "Two ways to be online" },
        { t: "p", text: "[[AR]] keeps you in your body with the Matrix drawn over the real world. [[VR]] drops your senses into the Matrix. VR is faster and stronger, but the risks are real. Try the three modes below." },
        { t: "widget", id: "modes", title: "Interface modes" },
        { t: "callout", tone: "rule", title: "Getting thrown out", text: "If you are kicked out of VR without switching to AR first, you suffer [[Dumpshock]]: 3 Stun in cold-sim, 3 Physical in hot-sim, resisted with Willpower. You are also disoriented and cannot gain or use Edge for (10 minus Willpower) minutes." },
        { t: "h", text: "What you need to hack" },
        { t: "p", text: "Everyone has a [[Commlink]]. It is enough for calls and searches. To make the Matrix do what you want, you need a [[Cyberdeck]], because the deck carries the four hacking numbers. Those numbers are the next lesson." },
        { t: "p", text: "Your gear forms a [[PAN]], a personal network. Hacked access is gained at the PAN level, not device by device, so one successful hack on your commlink can open everything linked to it." },
        { t: "book", query: "Matrix Access and PANs" },
        { t: "quiz", id: "matrix.q1a", q: "You are dumped out of cold-sim VR without warning. What happens?", options: ["Nothing, the filter protects you completely", "You take 3 Stun (dumpshock), resisted with Willpower", "You take 3 Physical, resisted with Body", "Your deck is bricked"], answer: 1, why: "Cold-sim filters the worst of it, but being yanked out still hurts: 3S. In hot-sim it is 3P." },
        { t: "quiz", id: "matrix.q1b", q: "What do you need to actually hack, not just browse?", options: ["A commlink", "A cyberdeck (or a technomancer's living persona)", "Any smartphone", "A sim module"], answer: 1, why: "The deck carries Attack, Sleaze, Data Processing and Firewall. Technomancers use their own minds instead." },
      ],
    },
    {
      id: "asdf",
      title: "Your four numbers: ASDF",
      blurb: "Attack, Sleaze, Data Processing, Firewall, and how to arrange them.",
      minutes: 6,
      blocks: [
        { t: "p", text: "In the real world you have Body, Agility and Strength. In the Matrix your physical attributes are replaced by four deck stats. Remember them as [[ASDF]]. Your mental attributes (Logic, Intuition, Willpower, Charisma) come along unchanged." },
        {
          t: "cards",
          items: [
            { title: "Attack", tag: "the crowbar", text: "Raw offence. How hard you hit in cybercombat, and what Brute Force and Data Spike run on." },
            { title: "Sleaze", tag: "the lockpick", text: "Stealth and trickery. How easily you slip in, hide and blend in. Probe and Backdoor Entry run on it." },
            { title: "Data Processing", tag: "the brain", text: "Computing power. How quick you are, how many programs you can run at once, and half of your defense." },
            { title: "Firewall", tag: "the armor vest", text: "Your main defense against hacking, and the dice you roll to resist Matrix damage." },
          ],
        },
        { t: "p", text: "A deck gives you a set of numbers, for example 5, 4, 3 and 2. **You decide which number sits on which stat**, and you can swap two of them as a Minor action (Reconfigure Matrix Attribute). A deck is a toolbox, not a fixed character sheet." },
        { t: "widget", id: "deck", title: "Arrange your deck" },
        { t: "callout", tone: "rule", title: "Two ratings that matter", text: "[[Attack Rating]] is Attack plus Sleaze. [[Defense Rating]] is Data Processing plus Firewall. You compare these against the other side's to see who gains Edge." },
        { t: "callout", tone: "warn", title: "Locked once you are in", text: "After you start a hack, you cannot swap your base Attack and Sleaze while you still hold access to the place you hacked. Data Processing and Firewall can still be rearranged." },
        { t: "callout", tone: "rule", title: "The wrong-tool penalty", text: "Some actions are linked to Attack (Brute Force, Data Spike, Tarpit) and some to Sleaze (Probe, Backdoor Entry). If you use an action linked to the lower of your two numbers, you take the difference as a dice pool penalty." },
        { t: "p", text: "A device also has a [[Matrix condition monitor]]: device rating divided by 2 (rounded up) plus 8 boxes. Every 3 full boxes of Matrix damage gives a minus 1 to tests made with it. Fill the monitor and the device is [[Bricked]]." },
        { t: "book", query: "Personas and Attributes" },
        { t: "quiz", id: "matrix.q2a", q: "Your deck is set to Attack 5 and Sleaze 2. You try a Probe, which is Sleaze-linked. What is the penalty?", options: ["None", "Minus 1 die", "Minus 3 dice", "Minus 5 dice"], answer: 2, why: "Probe uses Sleaze, your lower number. The penalty is the difference between the two: 5 minus 2 = 3 dice." },
        { t: "quiz", id: "matrix.q2b", q: "Which two stats make your Defense Rating?", options: ["Attack and Sleaze", "Data Processing and Firewall", "Sleaze and Firewall", "Attack and Data Processing"], answer: 1, why: "Defense Rating = Data Processing + Firewall. Attack + Sleaze is your Attack Rating." },
      ],
    },
    {
      id: "the-roll",
      title: "The one roll you need",
      blurb: "Skill plus attribute, hits, and who wins.",
      minutes: 5,
      blocks: [
        { t: "p", text: "Every Matrix test is a skill plus an attribute. Two skills do most of the work: [[Electronics]] for allowed actions and [[Cracking]] for forbidden ones. Both are normally paired with Logic." },
        { t: "formula", label: "Legal action", parts: ["Electronics", "+", "Logic"] },
        { t: "formula", label: "Illegal action", parts: ["Cracking", "+", "Logic"] },
        { t: "p", text: "The total is how many d6 you roll. Every 5 or 6 is a hit. In an opposed test the other side rolls the pool listed in the action, and whoever has more hits wins. The gap between the two is your [[Net hits]], and it often adds to the effect." },
        { t: "callout", tone: "rule", title: "Ties", text: "Ties typically go to the one who acted. When an effect needs net hits, you need at least one." },
        { t: "widget", id: "pool", title: "Roll it yourself" },
        { t: "callout", tone: "warn", title: "Glitches", text: "If more than half of your dice show a 1, that is a glitch. A glitch with zero hits is a critical glitch. A glitch on a Probe can even set off an alarm." },
        { t: "p", text: "Each action is either a [[Major action]] or a [[Minor action]]. Most hacking is Major, so expect roughly one real action per turn. Switching interface mode, entering or leaving a host, changing your icon, reconfiguring attributes and sending a message are Minor. Matrix Perception is Minor only if you have a deck, a cyberjack or a Resonance score." },
        { t: "quiz", id: "matrix.q3a", q: "Which dice pool fits a legal Matrix action?", options: ["Cracking + Logic", "Electronics + Logic", "Cracking + Intuition", "Electronics + Charisma"], answer: 1, why: "Legal tests use Electronics + Logic. Illegal ones use Cracking + Logic." },
        { t: "quiz", id: "matrix.q3b", q: "You roll 5, 6, 2, 1, 4, 5, 3. How many hits do you have?", options: ["2", "3", "4", "5"], answer: 1, why: "Only 5s and 6s are hits: the 5, the 6 and the second 5. That is 3." },
      ],
    },
    {
      id: "legal-illegal-os",
      title: "Legal, illegal and the Overwatch Score",
      blurb: "Why hackers get found, and the 40-point countdown.",
      minutes: 7,
      blocks: [
        { t: "p", text: "Every Matrix action is either [[Legal]] or [[Illegal]]. Sending a message, searching, editing a file you are allowed to touch: legal. Cracking a file, hacking into a host, crashing a program, snooping on traffic: illegal." },
        { t: "p", text: "The Matrix police, [[GOD]], keep a secret counter on you called your [[Overwatch Score]]. It starts at zero and only goes up." },
        {
          t: "list",
          items: [
            "**Performing an illegal action:** +1 OS for every hit the defender rolled, even if your hack still worked.",
            "**Using a hacking program** on an action: +1 OS each time. Just having it loaded costs nothing.",
            "**Holding illegal access:** +1 OS per round for each host where you hold illegal User access, and +3 OS per round for each host where you hold illegal Admin access.",
          ],
        },
        { t: "callout", tone: "rule", title: "Convergence at 40", text: "When your OS reaches 40, the device behind your last illegal action is [[Bricked]], you are dumped out of the Matrix with dumpshock, and your real-world location is reported to the authorities. Bonus Edge is lost as well." },
        { t: "widget", id: "os", title: "Watch the counter climb" },
        { t: "h", text: "How to keep it low" },
        {
          t: "list",
          items: [
            "**Prefer legal actions.** Matrix Perception, Matrix Search and Control Device are all legal.",
            "**Do not linger.** Illegal Admin access costs 3 OS every round. Ten rounds is 30 OS before you even roll a die.",
            "**Use a backdoor.** Admin gained through Backdoor Entry does not count as illegal Admin access, though illegal actions you take still add OS.",
            "**Know where you stand.** The Baby Monitor program tells you your OS for free. The Check OS action (Cracking + Logic, threshold 4, Admin access) is an illegal Major action.",
            "**Under the Radar.** With a cyberjack or Resonance you can spend 3 Edge so the next illegal action this turn adds no OS.",
            "**Reboot.** Rebooting resets your OS. Jacking out reboots the device you used.",
          ],
        },
        { t: "book", query: "Overwatch Score and Convergence" },
        { t: "quiz", id: "matrix.q4a", q: "You Probe a host and the defense rolls 3 hits. Your Probe succeeds anyway. What happens to your OS?", options: ["Nothing, you succeeded", "+3", "+1", "+3 only if you failed"], answer: 1, why: "OS goes up by the hits the defender rolled, whether or not you won the test." },
        { t: "quiz", id: "matrix.q4b", q: "You hold illegal Admin access to one host for 5 rounds. How much OS is that, before any rolls?", options: ["5", "10", "15", "40"], answer: 2, why: "Illegal Admin access costs 3 OS per round: 3 x 5 = 15." },
        { t: "quiz", id: "matrix.q4c", q: "Which way of holding Admin access is cheapest in Overwatch Score?", options: ["Brute Force straight to Admin", "Backdoor Entry after a successful Probe", "Brute Force to User, then wait", "Hash Check"], answer: 1, why: "Backdoor Entry gives Admin access that does not count as illegal Admin, so you skip the 3 OS per round." },
      ],
    },
    {
      id: "getting-in",
      title: "Getting in: Outsider, User, Admin",
      blurb: "Brute Force versus Probe, and why patience beats a hammer.",
      minutes: 8,
      blocks: [
        { t: "p", text: "Every system has three levels of access. Each action lists the level it needs." },
        { t: "widget", id: "ladder", title: "The access ladder" },
        { t: "p", text: "To get User or Admin access you hack in. There are two ways, and they are opposites." },
        {
          t: "cards",
          items: [
            { title: "Brute Force", tag: "Attack, Major action", text: "Fast and loud. You flood the target with junk until something breaks. It always alerts the target. If you fail you can try again next round. Straight to Admin without User access is harder: the defender gets +2 Firewall and +4 Defense Rating." },
            { title: "Probe", tag: "Sleaze, Extended, 1 minute", text: "Slow and quiet. You look for a weakness without tripping alarms, unless you glitch. A success creates a backdoor that lasts about (10 minus rating) hours or until you go offline. Net hits become bonus dice later." },
            { title: "Backdoor Entry", tag: "Sleaze, Major action", text: "Use the backdoor you made with Probe. Success gives Admin access that does not count as illegal Admin. If you fail, the backdoor is found and removed, and you must Probe again." },
          ],
        },
        { t: "widget", id: "entry", title: "Hammer or lockpick? Run the numbers" },
        { t: "callout", tone: "tip", title: "Rule of thumb", text: "Probe when you have time. Brute Force when the building is already on fire. And remember that a long Probe costs minutes, not rounds, so a guard patrolling on a schedule can beat you to it." },
        { t: "book", query: "Brute Force" },
        { t: "book", query: "Probe" },
        { t: "quiz", id: "matrix.q5a", q: "Which action always alerts the target?", options: ["Probe", "Backdoor Entry", "Brute Force", "Matrix Search"], answer: 2, why: "Brute Force always alerts. Probe does not unless you glitch." },
        { t: "quiz", id: "matrix.q5b", q: "Your Backdoor Entry fails. What now?", options: ["Try again immediately", "The backdoor is gone: you need to Probe again", "You are bricked", "You get User access instead"], answer: 1, why: "A failed Backdoor Entry means the exploit was detected and removed. You cannot try again until a new Probe makes a new one." },
      ],
    },
    {
      id: "edge",
      title: "Edge: why ratings matter",
      blurb: "Attack Rating versus Defense Rating, and Matrix Edge actions.",
      minutes: 5,
      blocks: [
        { t: "p", text: "In cybercombat and hacking, compare your Attack Rating with their Defense Rating, and their Attack Rating with yours. If one side is four or more points higher, that side gains a point of bonus [[Edge]]. Nobody can gain more than two bonus Edge in a round." },
        { t: "widget", id: "edge", title: "Who gets Edge?" },
        { t: "p", text: "Bonus Edge disappears when you leave a host, reboot your device, jack out, or when Convergence hits. Some programs grant or cancel Edge too." },
        { t: "h", text: "Matrix Edge actions" },
        { t: "p", text: "Everyone can use the normal Edge boosts on Matrix tests. If you have an implanted cyberjack or a Resonance score you get these extra ones:" },
        {
          t: "cards",
          items: [
            { title: "Emergency Boost", tag: "1 Edge", text: "Raise one Matrix attribute by 1 for a single test." },
            { title: "Hog", tag: "2 Edge", text: "Spam a host or persona with requests: its Data Processing drops by 2 and it loses an active program slot, for a number of rounds equal to your Attack Rating." },
            { title: "Signal Scream", tag: "2 Edge", text: "Your next action ignores any penalty from noise." },
            { title: "Under the Radar", tag: "3 Edge", text: "The next illegal action this turn does not add to your Overwatch Score. It does not make later actions legal." },
          ],
        },
        { t: "callout", tone: "tip", text: "If you build your deck so your Defense Rating is within 3 of what the IC will throw at you, they get no Edge advantage. One point can be the difference." },
        { t: "quiz", id: "matrix.q6a", q: "Your Attack Rating is 9 and the target's Defense Rating is 5. Result?", options: ["Nothing", "You gain 1 Edge", "You gain 2 Edge", "They gain 1 Edge"], answer: 1, why: "The gap is 4, so the higher side gains 1 bonus Edge. Bonus Edge from this is capped at 2 per round." },
      ],
    },
    {
      id: "hosts-and-ic",
      title: "Hosts, spiders and IC",
      blurb: "What guards a corporate network, and what each program does to you.",
      minutes: 8,
      blocks: [
        { t: "p", text: "A [[Host]] has a rating from 1 to 12. Its four stats are the rating, rating +1, rating +2 and rating +3, in any order. A rating 4 host might have Attack 5, Sleaze 4, Data Processing 7 and Firewall 6. The host and its security programs share those numbers." },
        { t: "p", text: "Security starts quiet. **Patrol IC** wanders the host making a Matrix Perception check every minute. If it spots you, the owners are told. A host can launch one more [[IC]] per combat round, up to its rating in programs at once, and only one copy of each type." },
        { t: "p", text: "Behind the IC may sit a [[Spider]], a living hacker. A host with a spider defends with the spider's Willpower plus the host's Firewall. An unwatched host just uses Firewall times two. IC use the host's Attack Rating, have a condition monitor of host rating times 2, and roll host rating times 2 for most tests." },
        { t: "widget", id: "ic", title: "The IC zoo" },
        { t: "callout", tone: "story", text: "Big sites nest several hosts behind each other, with the juiciest data in the deepest one. Your OS counts every host where you hold access, not only the one you are standing in." },
        { t: "book", query: "IC" },
        { t: "quiz", id: "matrix.q7a", q: "Which IC locks your connection so you cannot just log off?", options: ["Acid", "Tar Baby", "Marker", "Crash"], answer: 1, why: "Tar Baby link-locks you. Blaster does damage and link-locks. You then need a successful Jack Out test." },
        { t: "quiz", id: "matrix.q7b", q: "A rating 5 host throws Killer IC. You lose the opposed roll by 2 net hits. How much Matrix damage before soaking?", options: ["2", "5", "7", "10"], answer: 2, why: "Killer IC does net hits plus host rating: 2 + 5 = 7. You then roll Firewall to soak." },
      ],
    },
    {
      id: "cybercombat",
      title: "When it turns violent",
      blurb: "Data Spike, Tarpit, damage, link-lock and getting out alive.",
      minutes: 7,
      blocks: [
        { t: "p", text: "Cybercombat works like normal combat, only the target is an icon: IC, a security hacker's persona, a device. Attack Rating versus Defense Rating decides Edge, then you roll and compare hits." },
        {
          t: "cards",
          items: [
            { title: "Data Spike", tag: "Attack-linked", text: "Cracking + Logic against Data Processing + Firewall. Damage is half your Attack (rounded up) plus one box per net hit." },
            { title: "Tarpit", tag: "Attack-linked", text: "Same roll. Deals 1 plus net hits damage and cuts the target's Data Processing by the same amount. It recovers 1 point per round. At 0, the target cannot act." },
          ],
        },
        { t: "p", text: "Matrix damage goes to the device's condition monitor, and you resist it with your Firewall. [[Biofeedback]] damage skips the device and hurts the user, and you resist it with Willpower." },
        { t: "widget", id: "damage", title: "Take a hit" },
        { t: "callout", tone: "warn", title: "Link-lock", text: "[[Link-lock]] stops you from using Enter/Exit Host, Reboot Device or Switch Interface Mode. Your only way out is a Jack Out test (Electronics + Willpower) against whoever locked you. Even if you win, you usually still suffer dumpshock." },
        { t: "callout", tone: "tip", title: "Leave gracefully", text: "If you are not link-locked, switch to AR (a Minor action) before you Jack Out. No VR means no dumpshock." },
        { t: "quiz", id: "matrix.q8a", q: "A Data Spike with Attack 5 and 2 net hits. How much Matrix damage?", options: ["2", "3", "5", "7"], answer: 2, why: "Half of Attack 5 rounded up is 3, plus 2 net hits = 5." },
        { t: "quiz", id: "matrix.q8b", q: "You are link-locked in cold-sim VR. What can you do?", options: ["Switch to AR and log off", "Reboot your device", "Win a Jack Out test, then probably suffer dumpshock", "Wait it out"], answer: 2, why: "Link-lock blocks the easy exits. Jack Out beats it, but you usually take dumpshock." },
      ],
    },
    {
      id: "toolbox",
      title: "Your action toolbox",
      blurb: "Find the right action by what you want to do.",
      minutes: 6,
      blocks: [
        { t: "p", text: "There are about thirty Matrix actions, but you only need a handful for any job. Tell the finder what you want to do." },
        { t: "widget", id: "actions", title: "Action finder" },
        { t: "h", text: "Programs in one minute" },
        { t: "p", text: "Programs are small software boosts. How many can run at once is limited by your Data Processing." },
        {
          t: "cards",
          items: [
            { title: "Baby Monitor", tag: "basic", text: "Tells you your current Overwatch Score without spending an action." },
            { title: "Toolbox", tag: "basic", text: "Plus 1 Data Processing." },
            { title: "Signal Scrubber", tag: "basic", text: "Reduces noise by 2." },
            { title: "Overclock", tag: "hacking", text: "Adds two dice to a Matrix action." },
            { title: "Exploit", tag: "hacking", text: "Lowers a hacking target's Defense Rating by 2." },
            { title: "Stealth and Trace", tag: "hacking, Sleaze", text: "Gain 1 Edge on Hide or Trace Icon, to be spent as part of that action." },
          ],
        },
        { t: "callout", tone: "rule", text: "Remember the cost: each action you perform with a hacking program adds 1 OS." },
        { t: "book", query: "Matrix Actions" },
        { t: "quiz", id: "matrix.q9a", q: "You want a camera feed to loop so your team is not seen. Which action fits?", options: ["Data Spike", "Edit File", "Hash Check", "Jam Signals"], answer: 1, why: "Edit File changes, copies or deletes parts of a file or feed. It is a legal action, but you need User or Admin access, and you must repeat it each round to keep a continuous edit going." },
      ],
    },
    {
      id: "technomancers",
      title: "Technomancers in two minutes",
      blurb: "Hacking with a mind instead of a deck.",
      minutes: 4,
      blocks: [
        { t: "p", text: "A [[Technomancer]] needs no deck. They access the Matrix through a **living persona** that uses the same four ASDF stats, but derived from their mental attributes. They use [[Resonance]] the way a mage uses Magic." },
        {
          t: "cards",
          items: [
            { title: "No device, no brick", text: "Because they have no deck, they have no Matrix condition monitor. Matrix damage lands on their own Stun monitor unless stated otherwise." },
            { title: "Complex forms", text: "Resonance powers, a bit like spells for code. Each one is cast from a list the technomancer knows." },
            { title: "Sprites", text: "Helpers made from pure Resonance. A technomancer compiles them, registers them for tasks and sends them off to crack, fetch, repair or watch." },
            { title: "Submersion and echoes", text: "Their version of initiation: a deeper dive that raises their Resonance ceiling and unlocks new tricks." },
          ],
        },
        { t: "callout", tone: "story", text: "Technomancers are not Awakened and nobody knows exactly how they do what they do. Corps have studied them in ways you would not enjoy reading about, so many of them trust no one." },
        { t: "book", query: "Technomancers" },
        { t: "quiz", id: "matrix.q10", q: "A technomancer takes Matrix damage. Where does it go by default?", options: ["Their deck", "Their Stun condition monitor", "Their Physical monitor", "Nowhere"], answer: 1, why: "No deck means no Matrix condition monitor. Unless an effect says otherwise, the damage is Stun." },
      ],
    },
    {
      id: "playbook",
      title: "A hacker's playbook",
      blurb: "The order of operations, and the mistakes everyone makes once.",
      minutes: 5,
      blocks: [
        { t: "p", text: "Now you know every moving part. Here is how a clean job tends to go." },
        {
          t: "list",
          ordered: true,
          items: [
            "**Set up.** Pick AR or VR, arrange your ASDF for the job, load only the programs you need.",
            "**Scout with legal actions.** Matrix Search for public info. Matrix Perception to read the icons. Both are free of OS.",
            "**Get in quietly.** Probe, then Backdoor Entry. Brute Force only when you have to.",
            "**Do the job with legal actions where you can.** Control Device and Edit File are legal. Crack File and Hash Check are not, so keep them short.",
            "**Watch the clock.** Check OS, count rounds of illegal access, and decide your exit before you need it.",
            "**Leave gracefully.** Exit the host, switch to AR, then Jack Out. No dumpshock, no drama.",
          ],
        },
        { t: "h", text: "Five mistakes everybody makes once" },
        {
          t: "list",
          items: [
            "Brute forcing to Admin and sitting there. At 3 OS per round it ends in Convergence.",
            "Forgetting that Attack and Sleaze are locked once you are in.",
            "Fighting IC head on with a deck built for stealth.",
            "Jacking out of VR without switching to AR first.",
            "Ignoring OS until it is 35.",
          ],
        },
        { t: "callout", tone: "tip", text: "Ready to try it for real? The next page is a live run against a corporate host, with real dice and real consequences." },
      ],
    },
  ],
  sim: {
    title: "Ledger Lift at Corvid Freight",
    blurb: "Break into a freight company's host, steal a file, open a door for your team and get out clean. Your OS is the clock.",
    minutes: 15,
  },
  exam: [
    { id: "matrix.e1", q: "Which pair makes your Attack Rating?", options: ["Attack + Sleaze", "Data Processing + Firewall", "Attack + Firewall", "Sleaze + Data Processing"], answer: 0, why: "Attack Rating is Attack plus Sleaze. Defense Rating is Data Processing plus Firewall." },
    { id: "matrix.e2", q: "Your OS hits 40. What happens?", options: ["Nothing yet", "Your last illegal device is bricked, you are dumped and your location is reported", "You gain 2 Edge", "You must reboot after 10 minutes"], answer: 1, why: "That is Convergence." },
    { id: "matrix.e3", q: "You want Admin access but need to stay quiet. Best choice?", options: ["Brute Force", "Probe, then Backdoor Entry", "Data Spike", "Hash Check"], answer: 1, why: "Probe is quiet, and Backdoor Entry gives Admin that does not count as illegal Admin." },
    { id: "matrix.e4", q: "Which is a legal action?", options: ["Crack File", "Data Spike", "Control Device", "Snoop"], answer: 2, why: "Control Device uses Electronics + Logic and is legal. The others are illegal." },
    { id: "matrix.e5", q: "A defender rolls 4 hits against your Brute Force. You still win. OS change?", options: ["0", "+1", "+4", "+4 only if you lose"], answer: 2, why: "Illegal tests add the defender's hits to your OS whether you win or not." },
    { id: "matrix.e6", q: "How do you avoid dumpshock when leaving?", options: ["Reboot first", "Switch to AR, then Jack Out", "Run silent", "Spend 1 Edge"], answer: 1, why: "Dumpshock only hits you if you leave while in VR. Switching to AR is a Minor action." },
    { id: "matrix.e7", q: "Which IC drains your Firewall one point per net hit?", options: ["Acid", "Binder", "Jammer", "Marker"], answer: 0, why: "Acid cuts Firewall. Binder cuts Data Processing, Jammer cuts Attack, Marker cuts Sleaze." },
    { id: "matrix.e8", q: "Your Sleaze is lower than your Attack by 2. You use Brute Force. Penalty?", options: ["None, Brute Force uses Attack", "Minus 2", "Minus 4", "Minus 1"], answer: 0, why: "Brute Force is linked to Attack, your higher number. The penalty only applies when you use the action tied to your lower stat." },
    { id: "matrix.e9", q: "Your host has rating 5. How many IC can it run at once?", options: ["1", "3", "5", "10"], answer: 2, why: "Up to its rating in programs, one of each type." },
    { id: "matrix.e10", q: "Who keeps your Overwatch Score?", options: ["The host spider", "GOD, the Grid Overwatch Division", "Your deck", "Lone Star"], answer: 1, why: "GOD, the Matrix police." },
  ],
};
