import type { ModuleDef } from "../types";

export const MAGIC: ModuleDef = {
  id: "magic",
  title: "Magic for Dummies",
  tagline: "Throw fire without burning out. Summon spirits without losing your mind.",
  intro:
    "Eleven short lessons that turn the Magic chapter into plain language: how a spell becomes a dice roll, what drain really costs, how spirits work, and what the astral plane is for. Finish with a night job where every choice has a price.",
  glossary: {
    Magic: "Your magical attribute. It sets how many dice you roll with magic, how much damage your spells do, and how much magic you can safely control.",
    Awakened: "Anyone who can use magic: mages, adepts, aspected magicians, mystic adepts.",
    Mana: "The energy magic is made of. It flows through all living things.",
    Mage: "A magician who can do all three kinds of magic: spellcasting, conjuring and enchanting.",
    Adept: "A person who channels magic into their own body for physical gifts instead of casting spells. They buy powers with power points.",
    "Aspected magician": "A magician who only learns one part of magic, such as spellcasting only. In exchange they are better at it.",
    "Mystic adept": "A rare mix of mage and adept who splits their Magic between spells and powers.",
    Tradition: "The belief system your magic runs on. It decides which attribute you use to resist drain.",
    Hermetic: "A tradition of books, logic and formulas. Hermetic mages resist drain with Logic.",
    Shaman: "A tradition built on a mentor spirit and instinct. Shamans resist drain with Charisma.",
    Sorcery: "The skill for casting spells and similar magic.",
    Conjuring: "The skill for summoning and banishing spirits.",
    Enchanting: "The skill for making magical items, preparations and rituals.",
    "Spellcasting test": "Sorcery plus Magic. The roll you make to cast a spell.",
    Drain: "The strain of working magic. You resist it with a dice roll and take damage for what gets through.",
    "Drain Value": "The number you try to beat when resisting drain. Every spell has a base Drain Value, and tricks like Amp Up raise it.",
    "Amp Up": "Raise a Combat spell's damage by 1 per extra Drain Value of 2.",
    "Increase Area": "Widen an area spell by 2 meters of radius for 1 extra Drain Value.",
    "Direct Combat spell": "Magic that hurts the target itself. Cannot be dodged or armored against. Rolled against Willpower + Intuition.",
    "Indirect Combat spell": "Magic that makes something hurt the target, like fire or lightning. Rolled against Reaction + Willpower, and the target soaks damage with Body.",
    "Mana spell": "A spell that only affects living things and the astral plane. Walls and machines ignore it.",
    "Physical spell": "A spell that affects the physical world, like fire, a wall, or a mask over a camera.",
    Instantaneous: "A spell that happens once and is over.",
    Sustained: "A spell that lasts only as long as you keep it going. Every sustained spell costs you 2 dice on everything you do.",
    Limited: "A spell with a set end point. You can drop it early but cannot extend it.",
    Permanent: "A spell whose effect stays without effort once it is cast.",
    Force: "The power rating of a spirit, a focus or a ward.",
    Spirit: "A being from another plane that you can call and command. Types include air, beasts, earth, fire, kin and water.",
    Services: "Jobs a summoned spirit owes you. Each net hit on the summoning test is one service.",
    Summoning: "Calling a spirit. Conjuring + Magic against Force x 2.",
    Banishing: "Sending a spirit away. Conjuring + Magic against Force x 2, and net hits strip its remaining services.",
    Reagents: "Rare magical materials. Spending reagents equal to a spirit's Force gives you 1 bonus Edge when summoning or banishing it.",
    "Astral plane": "A second layer of reality laid over ours. Living things and magic show up bright there; machines and buildings are grey ghosts.",
    "Astral perception": "Seeing the astral plane while you are still in your body.",
    Assensing: "Reading an aura on the astral plane with Astral + Intuition. More hits, more detail.",
    "Astral projection": "Leaving your body behind and traveling in the astral plane as pure spirit.",
    "Astral signature": "The magical fingerprint spells and enchanted items leave behind. It fades over a number of hours equal to the caster's Magic.",
    "Mana barrier": "A magical wall. It blocks spells, spirits and astral forms, but you can usually walk through it in the physical world.",
    Essence: "A measure of how much of your living spark you still have. Cyberware and bioware cost it, and losing it costs Magic.",
    "Power points": "What adepts spend on powers. You get 1 per point of Magic.",
    Focus: "An enchanted item that boosts a magician's work.",
    Edge: "Your luck resource. A big gap in Attack Rating versus Defense Rating gives bonus Edge.",
    "Attack Rating": "For spells and astral fighting, Magic plus your tradition attribute.",
    "Defense Rating": "What the other side uses to defend. Compared with Attack Rating to see who gains Edge.",
    "Astral link": "A connection every spell, spirit and focus keeps to whoever made it. Skilled trackers can follow it back.",
    Metaplane: "The home world of a spirit.",
    "Spirit mindlink": "A silent mental link between you and the spirits you summon. You know instantly if one is banished.",
  },
  lessons: [
    {
      id: "what-is-magic",
      title: "What magic actually is",
      blurb: "Mana, the Awakened, and the four kinds of magic user.",
      minutes: 5,
      blocks: [
        { t: "p", text: "In the Sixth World magic is real, rare and measurable. It is a kind of energy called [[Mana]] that runs through every living thing. A small number of people, the [[Awakened]], can shape it." },
        { t: "p", text: "Do not think of magic as a separate game. It is the same dice you already know: a pool of d6, hits on 5 and 6, and a defender who rolls back. What changes is where the dice come from, and the price you pay afterward." },
        { t: "callout", tone: "story", text: "A street mage lights up a guard with a bolt of mana and walks away dizzy, with a headache like a hangover. The guard goes down. The mage will feel that bolt for the next hour. That headache is [[Drain]], and it is the heart of this module." },
        { t: "h", text: "Who can do what" },
        {
          t: "cards",
          items: [
            { title: "Mage", tag: "everything magic", text: "Spells, conjuring spirits, enchanting items. The most flexible, and the one with the most to keep track of. This module is mostly about mages." },
            { title: "Adept", tag: "magic in the body", text: "No spells. Instead you pour magic into your own body and buy powers like faster reflexes or a crushing punch. You get 1 power point for each point of Magic." },
            { title: "Aspected magician", tag: "one specialty", text: "A magician who only gets one slice of magic, such as spellcasting, conjuring or enchanting. A narrow toolbox, played deep." },
            { title: "Mystic adept", tag: "half and half", text: "A mix of mage and adept that splits Magic between spells and powers. Powerful and complicated, not where beginners should start." },
          ],
        },
        { t: "widget", id: "types", title: "Which Awakened would you be?" },
        { t: "h", text: "The three things magic does" },
        {
          t: "list",
          items: [
            "**Spellcasting** (skill: [[Sorcery]]). Instant effects: fire, healing, invisibility, mind control.",
            "**Conjuring** (skill: [[Conjuring]]). Calling and banishing spirits to work for you.",
            "**Enchanting** (skill: [[Enchanting]]). Making items and preparations that hold magic for later.",
          ],
        },
        { t: "p", text: "There is also a fourth world to know about: the [[Astral plane]]. It is where magic lives, and where you can see and fight what the physical world cannot. You will get there in lesson nine." },
        { t: "book", query: "Magic and the Awakened" },
        { t: "quiz", id: "magic.q1a", q: "Who gets power points?", options: ["Mages", "Adepts (and mystic adepts)", "Technomancers", "Everyone"], answer: 1, why: "Adepts buy powers with power points, one per point of Magic. Mages cast spells instead." },
        { t: "quiz", id: "magic.q1b", q: "What is [[Drain]]?", options: ["Magic leaking from your spell", "The strain you take from using magic", "A spell that hurts targets", "Losing your Essence"], answer: 1, why: "Drain is the damage you take from working magic. You roll to resist it every time you cast or conjure." },
      ],
    },
    {
      id: "your-numbers",
      title: "Your numbers",
      blurb: "Magic, Sorcery, tradition and the few pools you use over and over.",
      minutes: 5,
      blocks: [
        { t: "p", text: "A magician only needs to track a handful of numbers. Learn these and the rest of the module is just plugging them in." },
        {
          t: "cards",
          items: [
            { title: "Magic", tag: "attribute", text: "Your power. It is added to every magic dice pool, decides your base damage, and sets the limit for how much of your drain stays Stun." },
            { title: "Sorcery", tag: "skill", text: "How good you are at casting. Added to Magic for every spellcasting test." },
            { title: "Conjuring", tag: "skill", text: "How good you are at summoning and banishing. Added to Magic for those tests." },
            { title: "Tradition attribute", tag: "Logic or Charisma", text: "[[Hermetic]] mages use Logic. [[Shaman|Shamans]] use Charisma. It is the half of your drain resistance that depends on your tradition, and half of your Attack Rating." },
            { title: "Willpower", tag: "attribute", text: "The other half of drain resistance, and your damage resistance in astral fighting." },
          ],
        },
        { t: "formula", label: "Cast a spell", parts: ["Sorcery", "+", "Magic"] },
        { t: "formula", label: "Resist drain", parts: ["Willpower", "+", "Tradition attribute (Logic or Charisma)"] },
        { t: "formula", label: "Attack Rating for spells", parts: ["Magic", "+", "Tradition attribute"] },
        { t: "formula", label: "Summon or banish", parts: ["Conjuring", "+", "Magic"] },
        { t: "widget", id: "sheet", title: "Build your caster" },
        { t: "callout", tone: "rule", title: "Magic and machines do not mix", text: "[[Essence]] measures how much of your living spark you still have. Cyberware and bioware cost Essence, and every time your Essence drops below a whole number you lose a point of Magic. A mage covered in chrome is a weak mage." },
        { t: "book", query: "Magic attribute and Essence" },
        { t: "quiz", id: "magic.q2a", q: "A Hermetic mage resists drain with:", options: ["Willpower + Charisma", "Willpower + Logic", "Body + Logic", "Intuition + Logic"], answer: 1, why: "Hermetic: Willpower + Logic. Shamans use Willpower + Charisma." },
        { t: "quiz", id: "magic.q2b", q: "You have Magic 6, Sorcery 5, Logic 4. How many dice do you roll to cast a spell?", options: ["10", "11", "15", "9"], answer: 1, why: "Spellcasting is Sorcery + Magic = 5 + 6 = 11. Logic is for drain, not for casting." },
      ],
    },
    {
      id: "casting",
      title: "Casting a spell in three steps",
      blurb: "Adjust, roll, pay. Every spell works this way.",
      minutes: 7,
      blocks: [
        { t: "p", text: "Every spell in the game follows the same three steps. Combat spells add one extra step in the middle, which you will meet in lesson five." },
        {
          t: "list",
          ordered: true,
          items: [
            "**Adjust the spell.** Decide if you want to spend extra drain to make it stronger or wider. This is the only moment you can.",
            "**Roll the Spellcasting test.** [[Spellcasting test|Sorcery + Magic]]. Hits decide how well it works, or are compared against a defender.",
            "**Deal with drain.** Roll Willpower + your tradition attribute against the spell's [[Drain Value]]. Whatever you fail to resist hurts.",
          ],
        },
        { t: "h", text: "Step 1: the two knobs" },
        {
          t: "cards",
          items: [
            { title: "Amp Up", tag: "Combat spells only", text: "Add 1 point of base damage for each +2 Drain Value. Strong, expensive, and best saved for the one spell that must work." },
            { title: "Increase Area", tag: "Area spells only", text: "An area spell hits a 2 meter radius. Add 1 Drain Value for each extra 2 meters of radius." },
          ],
        },
        { t: "h", text: "Try one" },
        { t: "p", text: "Pick a spell, tune the knobs and cast it against two guards. Watch what the three steps do." },
        { t: "widget", id: "caster", title: "The three-step caster" },
        { t: "callout", tone: "tip", title: "Read the drain before you cast", text: "A spell's Drain Value is printed on the spell. If it is higher than the dice you have for drain, you will take damage most of the time. Plan for it." },
        { t: "book", query: "Casting Spells adjust the spell drain" },
        { t: "quiz", id: "magic.q3a", q: "You want a Fireball to hit a third guard standing 4 meters from the first two. What do you do?", options: ["Increase Area, +1 Drain Value", "Amp Up, +2 Drain Value", "Nothing, Fireball always hits everyone", "Roll Conjuring instead"], answer: 0, why: "Increase Area adds 2 meters of radius for +1 Drain Value. Amp Up changes damage, not area." },
        { t: "quiz", id: "magic.q3b", q: "Which is the right order?", options: ["Roll, adjust, drain", "Adjust, roll, drain", "Drain, adjust, roll", "Roll, drain, adjust"], answer: 1, why: "You decide the adjustments first, because the drain depends on them." },
      ],
    },
    {
      id: "drain",
      title: "Drain: the bill",
      blurb: "How drain is calculated, why it can go Physical, and how to budget it.",
      minutes: 7,
      blocks: [
        { t: "p", text: "[[Drain]] is the price of magic. After a cast, you roll Willpower plus your tradition attribute and compare your hits to the [[Drain Value]]." },
        {
          t: "list",
          items: [
            "**Hits equal to or above the Drain Value:** no damage.",
            "**Hits below the Drain Value:** you take Stun damage equal to the difference.",
            "**Damage higher than your Magic:** it becomes Physical damage instead of Stun.",
          ],
        },
        { t: "callout", tone: "warn", title: "Drain cannot be healed by magic", text: "Neither healing spells nor medkits fix drain damage. It heals the slow way. A caster who burns through Stun in the first fight has none left for the second." },
        { t: "widget", id: "drain", title: "Odds of drain damage" },
        { t: "h", text: "How casters keep it under control" },
        {
          t: "list",
          items: [
            "**Cast the cheapest spell that does the job.** A Stunbolt (Drain Value 3) takes down a guard for half the price of a Fireball.",
            "**Use Amp Up sparingly.** Each point of damage costs 2 Drain Value. Net hits often add the damage for free.",
            "**Do not stack Increase Area.** Wide spells are expensive. Hit the group you need and no more.",
            "**Spend Edge on the drain roll when it matters.** A reroll on the failed dice often saves you several boxes of Stun.",
            "**Remember the Physical rule.** If the unresisted drain is higher than your Magic, your body takes it for real.",
          ],
        },
        { t: "callout", tone: "story", text: "A rookie mage once cast a Fireball at full Amp Up in the first round of a fight. He won the round and lay down for the rest of it. Veterans pick the spell that ends the fight without ending them." },
        { t: "book", query: "Drain resistance Stun Physical" },
        { t: "quiz", id: "magic.q4a", q: "You roll 3 hits on your drain resistance. The spell's Drain Value was 6. Damage?", options: ["0", "3 Stun", "3 Physical", "6 Stun"], answer: 1, why: "6 minus 3 hits is 3. It is Stun unless 3 is higher than your Magic." },
        { t: "quiz", id: "magic.q4b", q: "Your Magic is 3. You take 5 drain damage after resisting. What type is it?", options: ["Stun", "Physical", "Half and half", "None"], answer: 1, why: "Drain damage becomes Physical when it is higher than your Magic." },
        { t: "quiz", id: "magic.q4c", q: "Can a Heal spell remove drain damage?", options: ["Yes", "No, drain cannot be healed by magic or medkits", "Only Stun", "Only Physical"], answer: 1, why: "Drain damage heals naturally. Magic and medkits do not touch it." },
      ],
    },
    {
      id: "combat-spells",
      title: "Combat spells: direct and indirect",
      blurb: "Two ways to hurt someone, and when each one wins.",
      minutes: 8,
      blocks: [
        { t: "p", text: "Combat spells add one step to the three. After you pick your targets, you compare [[Attack Rating]] and [[Defense Rating]] to see if anyone gains [[Edge]]. Your Attack Rating with spells is your **Magic plus your tradition attribute**. If it beats the target's Defense Rating by 4 or more, you gain 1 Edge. If you are behind by 4 or more, they do." },
        { t: "p", text: "Then the spell works in one of two ways." },
        {
          t: "cards",
          items: [
            { title: "Direct", tag: "the magic is the damage", text: "[[Direct Combat spell|Direct spells]] shape mana to hit the target itself. Roll Sorcery + Magic against the target's **Willpower + Intuition**. Net hits are the damage, plus any Amp Up. **The target does not resist the damage.** Examples: Manabolt, Stunbolt, Powerbolt." },
            { title: "Indirect", tag: "the magic makes something hurt", text: "[[Indirect Combat spell|Indirect spells]] create fire, lightning, ice or a blow. Roll Sorcery + Magic against **Reaction + Willpower**. Damage is **half your Magic (rounded up) + net hits + Amp Up**, and the target soaks it with **Body**. Examples: Fireball, Lightning Bolt, Clout." },
          ],
        },
        { t: "widget", id: "combat", title: "Direct versus indirect" },
        { t: "h", text: "Which one should I cast?" },
        {
          t: "list",
          items: [
            "**Armored target?** Direct spells ignore armor and soak. They are best against heavy opposition.",
            "**Low Willpower, high Body?** Direct beats a big brute. Indirect works better on someone with strong will but little Body.",
            "**Mana or Physical?** Mana spells (Manabolt, Stunbolt) need living targets. They do nothing to a drone. Physical spells hit machines too.",
            "**Stun or Physical?** Stun puts people down quietly and leaves them alive. Physical kills, and often makes a mess.",
            "**Loud or quiet?** Fire and lightning draw attention. A Stunbolt does not.",
          ],
        },
        { t: "callout", tone: "rule", title: "The classic spells", text: "Stunbolt (DV 3, Stun, single), Stunball (DV 4, Stun, area), Manabolt (DV 4, Physical, direct), Manaball (DV 5, area), Powerbolt (DV 4), Powerball (DV 5), Clout (DV 3, Stun, indirect), Blast (DV 4, area), Flamestrike (DV 5), Fireball (DV 6, area), Lightning Bolt (DV 5), Lightning Ball (DV 6, area)." },
        { t: "book", query: "Combat Spells Direct Indirect" },
        { t: "quiz", id: "magic.q5a", q: "A Direct Combat spell is rolled against:", options: ["Reaction + Willpower", "Willpower + Intuition", "Body + Reaction", "Logic + Intuition"], answer: 1, why: "Direct spells are opposed by Willpower + Intuition. Indirect spells are opposed by Reaction + Willpower." },
        { t: "quiz", id: "magic.q5b", q: "Who resists the damage of an Indirect Combat spell?", options: ["Nobody", "The target, with Body", "The caster, with Willpower", "The target, with Willpower"], answer: 1, why: "Indirect spells create a physical effect, so the target rolls Body to soak. Direct spell damage is not resisted." },
        { t: "quiz", id: "magic.q5c", q: "You have Magic 6 and Charisma 5. The guards have a Defense Rating of 7. Do you gain Edge?", options: ["No", "Yes, 1", "Yes, 2", "Only if you roll hits"], answer: 1, why: "Your Attack Rating is Magic + tradition attribute = 11. The gap is 4, which gives you 1 Edge." },
      ],
    },
    {
      id: "other-spells",
      title: "The other four spell families",
      blurb: "Detection, Health, Illusion, Manipulation. And what holding a spell costs.",
      minutes: 7,
      blocks: [
        { t: "p", text: "Fire is not the only thing mages do. The other four categories solve the problems that do not involve a body count." },
        {
          t: "cards",
          items: [
            { title: "Detection", tag: "senses", text: "Find, identify, see through. Detect Life, Analyze Device, Mind Probe." },
            { title: "Health", tag: "bodies", text: "Heal wounds, cure toxins, boost reflexes. Heal removes 1 box of damage per net hit, but it does not fix drain." },
            { title: "Illusion", tag: "minds", text: "Fool senses or thoughts. Invisibility, Mask, Hush, Phantasm. Single-Sense spells fool one sense. Multi-Sense fool all. Some fool living beings and some fool machines." },
            { title: "Manipulation", tag: "matter", text: "Move, shape and change the world. Walls, telekinesis, mental control." },
          ],
        },
        { t: "h", text: "Four numbers on every spell" },
        {
          t: "list",
          items: [
            "**Range:** Touch, Line of Sight (LOS), LOS (A) for an area, or Special.",
            "**Type:** M for [[Mana spell|mana]] (living things and astral only) or P for [[Physical spell|physical]] (the real world, machines included).",
            "**Duration:** [[Instantaneous|Instantaneous (I)]], [[Sustained|Sustained (S)]], [[Limited|Limited (L)]] or [[Permanent|Permanent (P)]].",
            "**Drain Value (DV):** what you will resist after casting.",
          ],
        },
        { t: "callout", tone: "warn", title: "Sustaining is not free", text: "While a [[Sustained]] spell is running, you take **minus 2 dice on every action** for each one. Two spells held at once means minus 4 on your attack, your drain resistance and your defense. Dropping a sustained spell takes no action." },
        { t: "widget", id: "sustain", title: "The sustain tax" },
        { t: "h", text: "Browse the spells" },
        { t: "widget", id: "catalog", title: "Spell browser" },
        { t: "callout", tone: "tip", text: "Invisibility only fools living eyes. Cameras see right through it. For a camera, you need Improved Invisibility (which fools tech too) or a spell like Sensor Sneak. Picking the wrong one is how stealth runs end." },
        { t: "book", query: "Illusion Spells Invisibility" },
        { t: "quiz", id: "magic.q6a", q: "You hold two Sustained spells. How many dice do you lose on your attack roll?", options: ["2", "4", "0", "1"], answer: 1, why: "Minus 2 for each spell you sustain: 2 x 2 = 4." },
        { t: "quiz", id: "magic.q6b", q: "A mana spell hits:", options: ["Anything", "Only living beings and astral things", "Only machines", "Only spirits"], answer: 1, why: "Mana spells interact with the astral plane, and living beings have an astral side. Machines do not." },
        { t: "quiz", id: "magic.q6c", q: "What does Improved Invisibility do that plain Invisibility does not?", options: ["Lasts longer", "Fools cameras and other technology too", "Costs less drain", "Hides you from spirits"], answer: 1, why: "The improved version works against technology as well as living eyes." },
      ],
    },
    {
      id: "summoning",
      title: "Summoning spirits",
      blurb: "Pick a Force, roll, and walk away with services.",
      minutes: 8,
      blocks: [
        { t: "p", text: "[[Summoning]] is the second pillar of magic. You call a [[Spirit]] from its home plane, and it does what you ask for a short time." },
        { t: "p", text: "It is not a spell. It uses the [[Conjuring]] skill and a different roll." },
        {
          t: "list",
          ordered: true,
          items: [
            "**Choose the Force.** Higher Force means a stronger spirit and a harder summon.",
            "**Roll Conjuring + Magic** against **Force x 2**. You need at least 1 net hit to succeed.",
            "**Services equal your net hits.** Each one is a single job.",
            "**Resist drain** equal to the number of hits the spirit rolled (not net hits).",
          ],
        },
        { t: "widget", id: "summon", title: "Summon a spirit" },
        { t: "h", text: "What counts as a service" },
        { t: "p", text: "A [[Services|service]] is one clear, specific action. \"Take this package to Mr. Johnson\" is a service. \"Keep me safe\" is not. \"Distract those guards for ten minutes\" is. The gamemaster has the last word on what is specific enough." },
        { t: "callout", tone: "rule", title: "Limits and clocks", text: "The total Force of all your active spirits cannot exceed Magic x 3. A spirit leaves after one sunrise and one sunset, even with services unspent. If the drain knocks you unconscious, the spirit goes home at once." },
        { t: "callout", tone: "tip", title: "Reagents", text: "[[Reagents]] equal to the spirit's Force give you 1 bonus Edge on the summoning test. It is cheap insurance for a Force 5 or 6 spirit." },
        { t: "callout", tone: "story", text: "A Force 6 spirit might be a fantastic bodyguard. It also rolls 12 dice against your 11, and rolls plenty of hits in the drain test. Greedy conjurers learn this in the form of an unconscious body and a spirit that quietly goes home." },
        { t: "book", query: "Summoning Conjuring Services" },
        { t: "quiz", id: "magic.q7a", q: "You summon a Force 4 spirit. What do you roll against?", options: ["4", "8", "12", "Its Willpower"], answer: 1, why: "The spirit rolls Force x 2, so 8 dice." },
        { t: "quiz", id: "magic.q7b", q: "You get 4 hits, the spirit gets 2. How many services, and how much drain?", options: ["4 services, 4 drain", "2 services, 2 drain", "2 services, 4 drain", "4 services, 2 drain"], answer: 1, why: "Services equal net hits (4 - 2 = 2). Drain equals the spirit's hits (2), not net hits." },
        { t: "quiz", id: "magic.q7c", q: "With Magic 5, what is the largest total Force you can have active?", options: ["5", "10", "15", "20"], answer: 2, why: "Magic x 3 = 15 total Force across all your spirits." },
      ],
    },
    {
      id: "spirits",
      title: "Spirits and banishing",
      blurb: "What the six spirit types are good at, and how to send one home.",
      minutes: 7,
      blocks: [
        { t: "p", text: "There are six types of spirit in the core rules. Four are elemental, one is animal-like and one is person-like. Their stats all grow with Force." },
        { t: "widget", id: "spirits", title: "Spirit stats by Force" },
        {
          t: "cards",
          items: [
            { title: "Air", tag: "fast and hard to hit", text: "Very high Reaction, so excellent at disrupting and pursuing. Low Strength. Good for interference and scouting." },
            { title: "Earth", tag: "slow and tough", text: "The highest Body and Strength. Hard to damage. The classic bodyguard." },
            { title: "Fire", tag: "damage dealer", text: "High Agility and Reaction, plus a natural fire attack." },
            { title: "Water", tag: "all-rounder", text: "Balanced, with a strong Reaction. Allergic to fire." },
            { title: "Beasts", tag: "the bruiser", text: "Strong and physical, with sharp senses. Good at following and finding." },
            { title: "Kin", tag: "the thinker", text: "Closest to a person. Can use one of your spells as an innate effect at higher Force." },
          ],
        },
        { t: "h", text: "Banishing" },
        { t: "p", text: "[[Banishing]] is the flip side. Use a Major action and roll **Conjuring + Magic** against the spirit's **Force x 2**. Each net hit strips one of the spirit's remaining services. At zero, it goes home." },
        { t: "p", text: "Banishing also costs drain, and it is bigger than summoning: **twice the spirit's hits**. It is Stun unless it is higher than your Magic." },
        { t: "widget", id: "banish", title: "Banish a spirit" },
        { t: "callout", tone: "tip", text: "Spirits can be hurt with anything that affects astral beings, or by regular weapons if they materialize. They have one condition monitor of (Force / 2) + 8 boxes. Fill it and the spirit is sent home." },
        { t: "callout", tone: "rule", title: "Spirits and Edge", text: "Spirits cannot gain Edge for themselves or for you, but they still have an Attack Rating. You can spend 2 of your Edge to give a spirit 1 Edge, if it is within Force x 10 meters." },
        { t: "book", query: "Spirits Force banishing" },
        { t: "quiz", id: "magic.q8a", q: "You banish a Force 5 spirit with 3 net hits. It had 2 services left. What happens?", options: ["Nothing", "It goes home", "It gains a service", "You summon it again"], answer: 1, why: "Each net hit strips a service. 3 net hits is more than the 2 it had, so it leaves." },
        { t: "quiz", id: "magic.q8b", q: "The spirit rolled 3 hits against your banishing. What drain do you resist?", options: ["3", "6", "1", "9"], answer: 1, why: "Banishing drain is twice the spirit's hits: 2 x 3 = 6." },
        { t: "quiz", id: "magic.q8c", q: "Which spirit type is the toughest in a fight?", options: ["Air", "Earth", "Fire", "Kin"], answer: 1, why: "Spirits of earth have the highest Body and Defense Rating of the six types." },
      ],
    },
    {
      id: "astral",
      title: "The astral plane",
      blurb: "Seeing auras, leaving your body, and fighting in a place with no walls.",
      minutes: 8,
      blocks: [
        { t: "p", text: "The [[Astral plane]] lies over our world like a second skin. Living things and magic glow on it. Machines, buildings and furniture are dim grey ghosts." },
        { t: "h", text: "Three levels of access" },
        {
          t: "cards",
          items: [
            { title: "Astral perception", tag: "look, from your body", text: "You stay in your body and see both worlds at once. Spells, auras and spirits become visible. Magicians and some adepts can do this." },
            { title: "Assensing", tag: "read an aura", text: "Roll Astral + Intuition on an aura you can see. More hits tell you more: mood, health, Essence, whether a spell is active, the kind of astral signature." },
            { title: "Astral projection", tag: "leave your body", text: "Your soul steps out and travels freely. Your body stays behind, helpless. You are fast, you can walk through walls, and you are on a clock." },
          ],
        },
        { t: "h", text: "Rules of the road" },
        {
          t: "list",
          items: [
            "**You are fast.** Astral running is about 5 kilometers per combat round. Astral walking is 100 meters per round, slow enough to look around.",
            "**Walls do not stop you.** Buildings and cars are ghosts. The earth itself blocks astral forms, so underground vaults are astral-safe.",
            "**Details are lost.** You cannot read a screen or see papers on a desk. You get layout and living things, not text.",
            "**You can manifest.** A Major action makes you visible as a faint ghost. You cannot touch things, and cameras do not see you.",
            "**You have a curfew.** You can stay out for Magic x 2 hours. After that you lose 1 Essence for each extra hour. At zero Essence you die.",
          ],
        },
        { t: "widget", id: "astral", title: "The astral clock" },
        { t: "h", text: "Astral signatures and links" },
        { t: "p", text: "Every spell, spirit and enchanted item leaves an [[Astral signature]] tied to its maker. Signatures fade over a number of hours equal to the caster's Magic. A tidy caster uses the Cleanse action to scrub them. A careful investigator follows an [[Astral link]] back to the source." },
        { t: "h", text: "Fighting astrally" },
        {
          t: "list",
          items: [
            "**Attack Rating:** Magic + tradition attribute.",
            "**Defense Rating:** Intuition plus innate armor. Your physical armor does not count.",
            "**Unarmed:** Astral + Willpower against the defender's Intuition + Logic. Damage is half your tradition attribute (rounded up) plus net hits.",
            "**Spells:** Mana spells only. Sorcery + Magic as usual.",
            "**Soaking:** Willpower. The attacker chooses Stun or Physical.",
          ],
        },
        { t: "callout", tone: "rule", title: "Mana barriers", text: "A [[Mana barrier]] is a magical wall. It blocks spells, spirits, manifesting entities and astral travelers. Its rating is added to the defense pool of anything cast through it. You can usually walk through one in the physical world. Barriers do not stop their own creators." },
        { t: "callout", tone: "warn", text: "Your body is defenceless while you project. Someone else should watch it. Mages have woken up in the back of a van, miles from where they left." },
        { t: "book", query: "The Astral Plane projection assensing" },
        { t: "quiz", id: "magic.q9a", q: "How long can you stay astrally projected with Magic 5 before it starts hurting?", options: ["5 hours", "10 hours", "1 hour", "No limit"], answer: 1, why: "You can stay out for Magic x 2 hours. After that you lose 1 Essence per extra hour." },
        { t: "quiz", id: "magic.q9b", q: "What skill do you roll to read an aura?", options: ["Sorcery + Magic", "Astral + Intuition", "Perception + Logic", "Conjuring + Intuition"], answer: 1, why: "Assensing uses the Astral skill with Intuition." },
        { t: "quiz", id: "magic.q9c", q: "Why does a wall not stop an astral traveler?", options: ["Magic breaks it", "Manufactured objects are only grey ghosts on the astral", "Astral forms are fast", "They do not, it does"], answer: 1, why: "Buildings and vehicles have only a faint grey presence on the astral. Living things, spirits and mana barriers are solid there." },
      ],
    },
    {
      id: "adepts-and-limits",
      title: "Adepts and the limits of magic",
      blurb: "Magic in the body, and the things magic cannot do.",
      minutes: 5,
      blocks: [
        { t: "p", text: "Not every Awakened runner throws fire. Some channel magic inward." },
        { t: "h", text: "Adepts" },
        { t: "p", text: "An [[Adept]] has no spells. Their Magic becomes [[Power points]], which they spend on powers. Powers are either always on or switch on with an action." },
        {
          t: "list",
          items: [
            "**Combat Sense:** bonus dice on defense tests.",
            "**Critical Strike:** your melee attacks do more damage.",
            "**Improved Agility, Reflexes, Close Combat and so on:** your body just works better.",
            "**Astral Perception:** an adept can buy it. Without it, they cannot see the astral plane.",
          ],
        },
        { t: "callout", tone: "tip", text: "Adepts skip the casting roll, the sustaining penalty and most of the drain a mage deals with. The price is that they cannot cast spells or summon, and they need a power to see the astral plane." },
        { t: "h", text: "What magic cannot do" },
        {
          t: "list",
          items: [
            "Magic cannot change Edge, Essence, Magic or Resonance.",
            "Mana spells do nothing to objects and machines.",
            "Drain cannot be healed by magic.",
            "A mana barrier stops most spells cold.",
            "Technology wears on magic: lost Essence is lost Magic.",
          ],
        },
        { t: "h", text: "Foci and enchanting" },
        { t: "p", text: "A [[Focus]] is an enchanted item that stores magical support: it boosts spellcasting, helps with spirits or adds to a weapon. Foci are linked to the magician who activated them, which is useful for allies and dangerous if you are tracked." },
        { t: "book", query: "Adept powers power points" },
        { t: "quiz", id: "magic.q10a", q: "An adept has Magic 4. How many power points?", options: ["2", "4", "8", "None"], answer: 1, why: "1 power point per point of Magic." },
        { t: "quiz", id: "magic.q10b", q: "Which is true of an adept?", options: ["They cast spells with less drain", "They buy powers with power points instead of casting spells", "They can summon spirits", "They are immune to spells"], answer: 1, why: "Adepts spend power points on powers instead of casting spells, so they skip the casting roll and the drain that comes with it." },
      ],
    },
    {
      id: "playbook",
      title: "A mage's playbook",
      blurb: "Turn the rules into good decisions at the table.",
      minutes: 5,
      blocks: [
        { t: "p", text: "You know all the moving parts. Here is how a magician stays useful for a whole run and not just the first fight." },
        {
          t: "list",
          ordered: true,
          items: [
            "**Look first.** Astral perception or a Detection spell shows you who is Awakened, where the wards are and what is hiding. It costs almost nothing.",
            "**Pick the quiet option.** Stunbolt over Fireball. Invisibility over a fight. A fight you skipped costs zero drain.",
            "**Count your drain pool.** Know how many dice you resist with, compare it to the Drain Value, and decide before you cast.",
            "**Spend Stun like a budget.** Ten or so boxes is a whole run. A single Amp Up can eat a third of them.",
            "**Do not sustain what you do not need.** Every sustained spell costs 2 dice on everything.",
            "**Hold a spirit in reserve.** A Force 3 or 4 spirit with 2 services can carry a scene while you recover.",
            "**Keep Edge for drain.** A reroll on a bad drain roll is often worth more than a rerolled attack.",
          ],
        },
        { t: "h", text: "Five mistakes everyone makes once" },
        {
          t: "list",
          items: [
            "Casting a Fireball in a hallway and discovering it is also a fire alarm.",
            "Holding Invisibility and Improved Invisibility together, then missing everything for 4 dice.",
            "Summoning a spirit with more Force than you can survive drain from.",
            "Projecting astrally with nobody watching your body.",
            "Spending all your Stun in the first scene.",
          ],
        },
        { t: "callout", tone: "tip", text: "Ready to try it for real? The next page is a night job with live dice. Every spell costs drain. The best run is the one where you barely cast anything at all." },
      ],
    },
  ],
  sim: {
    title: "Night Job at Halcyon Biolab",
    blurb: "Slip into a lab after dark, steal a sample, and decide for every obstacle whether magic is worth its price.",
    minutes: 15,
  },
  exam: [
    { id: "magic.e1", q: "What do you roll to cast a spell?", options: ["Magic + Logic", "Sorcery + Magic", "Conjuring + Magic", "Sorcery + Willpower"], answer: 1, why: "Spellcasting is Sorcery + Magic." },
    { id: "magic.e2", q: "A Hermetic mage resists drain with:", options: ["Willpower + Charisma", "Willpower + Logic", "Body + Willpower", "Magic + Willpower"], answer: 1, why: "Hermetic means Logic. Shamans use Charisma." },
    { id: "magic.e3", q: "A spell has Drain Value 6. You roll 4 hits on drain. Damage?", options: ["0", "2", "4", "6"], answer: 1, why: "6 minus 4 = 2. It is Stun unless it is higher than your Magic." },
    { id: "magic.e4", q: "When does drain turn into Physical damage?", options: ["When you roll a glitch", "When the damage is higher than your Magic", "Always for Combat spells", "When you sustain a spell"], answer: 1, why: "If the damage left after the resistance test is higher than your Magic, it is Physical." },
    { id: "magic.e5", q: "What does Amp Up do?", options: ["Widens the area", "Adds 1 base damage per +2 Drain Value on a Combat spell", "Adds dice to your casting", "Reduces drain"], answer: 1, why: "Amp Up raises damage on Combat spells at +2 Drain Value for each point." },
    { id: "magic.e6", q: "Which Combat spell type lets the target soak damage with Body?", options: ["Direct", "Indirect", "Both", "Neither"], answer: 1, why: "Indirect spells create a physical effect, so the target rolls Body." },
    { id: "magic.e7", q: "You sustain three spells. How many dice do you lose on each action?", options: ["3", "6", "2", "9"], answer: 1, why: "Each sustained spell costs 2 dice: 3 x 2 = 6." },
    { id: "magic.e8", q: "You get 5 hits summoning a spirit that got 3. Services and drain?", options: ["5 services, 3 drain", "2 services, 3 drain", "2 services, 5 drain", "3 services, 2 drain"], answer: 1, why: "Services = net hits (2). Drain = the spirit's hits (3)." },
    { id: "magic.e9", q: "Magic 6. How much total Force can your active spirits have?", options: ["6", "12", "18", "24"], answer: 2, why: "The limit is Magic x 3 = 18." },
    { id: "magic.e10", q: "Banishing drain equals:", options: ["The spirit's hits", "Twice the spirit's hits", "Your net hits", "The spirit's Force"], answer: 1, why: "Banishing drain is twice the number of hits the spirit rolled." },
    { id: "magic.e11", q: "Which of these can an astrally projecting mage do?", options: ["Read a paper on a desk", "Pass through a wall", "Cast Fireball on a guard", "Pick up a key"], answer: 1, why: "The astral plane ignores buildings, but you cannot read text, touch objects or hit physical targets with spells." },
    { id: "magic.e12", q: "Magic 5. How many hours can you project before Essence loss begins?", options: ["5", "10", "15", "No limit"], answer: 1, why: "Magic x 2 hours." },
  ],
};
